# Generated by Django 5.2.6 on 2025-10-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tablero_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia', models.CharField(blank=True, max_length=255, null=True, verbose_name='presupuesto')),
                ('recibio', models.CharField(blank=True, max_length=255, null=True, verbose_name='recibio')),
                ('estado', models.CharField(blank=True, choices=[('En evaluación', 'En evaluación'), ('En espera', 'En espera'), ('En reparación', 'En reparación'), ('Entregado', 'Entregado')], default='En evaluación', max_length=255, null=True, verbose_name='Estado')),
                ('cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recepción')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
            },
        ),
    ]
