# Generated by Django 5.2.6 on 2025-10-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero_model',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='tablero_model',
            name='lista',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de lista'),
        ),
        migrations.AlterField(
            model_name='tablero_model',
            name='estado',
            field=models.CharField(blank=True, choices=[('Evaluación', 'Evaluación'), ('Espera', 'Espera'), ('Reparación', 'Reparación'), ('Entregado', 'Entregado')], default='Evaluación', max_length=255, null=True, verbose_name='Estado'),
        ),
    ]
