# Generated by Django 5.2.6 on 2025-10-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0002_tablero_model_desc_tablero_model_lista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero_model',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagen'),
        ),
    ]
