# Generated by Django 5.2.6 on 2025-10-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0003_alter_tablero_model_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablero_model',
            name='estado',
        ),
        migrations.AlterField(
            model_name='tablero_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
