# Generated by Django 5.2.6 on 2025-11-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0004_remove_tablero_model_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
